### ISSUE TITLE
LS 6

### ISSUE THREAD

**Issue by SMAPPER** [sw-jung/logstash-filter-memoize#1]
Do you know if an update is needed to get logstash-filter-memoize to work with Logstash 6? I am using the following code snippet and it continues to error:

memoize {
        key => "%{highest_registered_domain}"
        fields => [ "rank" ]
        filter_name => "elasticsearch"
        filter_options => {
        elasticsearch {
            query => "highest_registered_domain:%{highest_registered_domain}"
            index => "alexa-top1m"
            fields => {
                "rank" => "rank"
            }
        }
    }

This code snippet works on Logstash 5. WIthout memoize (using the below code) it works.

elasticsearch {
  query => "highest_registered_domain:%{highest_registered_domain}"
  index => "alexa-top1m"
  fields => {
    "rank" => "rank"
}

The error I receive is:

[ERROR] 2017-11-20 13:40:16.780 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] agent - Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"NoMethodError", :message=>"undefined method `get' for {\"rank\"=>\"rank\"}:Hash\nDid you mean?  gem", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:210:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:202:in `expr'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:133:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:98:in `expr_attributes'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:76:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:69:in `expr'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:48:in `block in compile'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:46:in `compile'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:46:in `compile_ast'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:50:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:54:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:107:in `compile_lir'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:215:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}

Any thoughts? This is a truly amazing plugin and I'm doing my best to share it with the community.

**Comment by sw-jung** [comment]
@SMAPPER Thanks for your issue!

I have not tested on logstash-6.x.

I'll solve it as soon as possible.

**Comment by sw-jung** [comment]
@SMAPPER 

Unfortunately, logstash-6.x nested hash does not seem to be compiled.

I have registered [an issue](https://github.com/elastic/logstash/issues/8701) and now considering spec changes.

**Comment by sw-jung** [comment]
This issue resolved at logstash version 6.0.1.

See [Logstash 6.0.1 Release Notes](https://www.elastic.co/guide/en/logstash/6.0/logstash-6-0-1.html#logstash-6-0-1).
> Fixed bug where plugins that used nested hashes for configuration would not work correctly
